services:
  - type: web
    name: game-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production

  - type: web
    name: game-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_WS_URL
        value: wss://game-backend.onrender.com 